local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', function()
    builtin.find_files({})
end)
vim.keymap.set('n', '<C-p>', function()
    builtin.git_files({})
end)
vim.keymap.set('n', '<leader>ps', function ()

builtin.grep_string({ search = vim.fn.input("Grep > ") })

end)
vim.keymap.set('n', '<leader>fg',function()
    builtin.buffers ({}) 
end)
vim.keymap.set('n', '<leader>fh',function()
    builtin.help_tags ({}) 
end)
vim.keymap.set('n', '<leader>ff',function()
    builtin.find_files({}) 
end)
